Replace fread with mmap
jserv/semu pull request #18
Opened 2023-07-13 11:42 UTC by zoanana990

Replace `fread` with `mmap` method

Performance comparison
Load Linux image:
- fread method:  18446744073709535686 clock
- mmap method:                                       157 clock

2023-07-13 12:04 UTC, jserv commented on main.c
> +#include <time.h>
The inclusion `time.h` is redundant.

2023-07-13 12:05 UTC, jserv requested changes
Use [atexit(3)](https://man7.org/linux/man-pages/man3/atexit.3.html) to perform the `munmap` operation.

2023-07-13 12:06 UTC, jserv commented
Check https://github.com/jserv/semu/blob/master/CONTRIBUTING.md carefully and ensure the consistent style.

2023-07-15 07:52 UTC, jserv commented
Any update?

2023-07-16 10:27 UTC, zoanana990 commented
yes, coding style was changed, but  i don't know why i need to use atexit(3) to perform the munmap operation, is this for error handling? like the following code:

```c
void cleanup(*addr, size_t len)
{
    munmap(...)
}
static void read_file_into_ram(char **ram_loc, const char *name)
{
...
    if (*ram_loc == MAP_FAILED) {
        fprintf(stderr, "mmap failed\n");
        atexit(cleanup);
    }
}
```

2023-07-16 14:19 UTC, jserv commented
> yes, coding style was changed, but i don't know why i need to use atexit(3) to perform the munmap operation, is this for error handling? like the following code:

No, `atexit` is invoked right after `mmap` succeeds. It is used for normal execution path rather than the abnormal one. i.e., exception handling.

2023-07-17 10:46 UTC, jserv commented
Superseded by commit 944a51d612aef623b51ebcdd4956336bae61e0a6

2023-07-17 10:46 UTC, closed without merging

2023-07-17 10:47 UTC, jserv commented
Thank @zoanana990 for contributing.