Integrate riscv-tests for ISA unit test
jserv/semu pull request #3
Opened 2022-07-15 09:11 UTC by gagachang

As the discussion in the issue ticket.
This patch first supports **./semu  --test** command to run all test binaries and show the test result like:

```
$ make test
cc -O2 -Wall -Iinclude -o semu semu.c test/test.c -lpthread
./semu --test
Test binary rv64ui_p_fence_i failed...
An exception occurred.
Test binary rv64ua_p_amoadd_w failed...
Fail test case = 2.
Test binary rv64ua_p_amoand_d failed...
An exception occurred.
Pass: rv64ui_p_add
Pass: rv64ui_p_addi
Pass: rv64ui_p_addiw
Pass: rv64ui_p_addw
Pass: rv64ui_p_and
Pass: rv64ui_p_andi
Pass: rv64ui_p_auipc
Fail: rv64ui_p_fence_i
...
Pass: rv64ui_p_jal
...
Pass: rv64ua_p_amoadd_d
Fail: rv64ua_p_amoadd_w
Fail: rv64ua_p_amoand_d
=======================
Test result: 51/54
=======================
```

A new entry point is declared to execute test flow.
And a new C file **./test/test.c** and related header are created for information of test binaries.
Note that I just put parts of the test binaires into this patch.

I think there are many spaces to optimize this patch.
Please review this patch and give some advices, thanks.

2022-07-15 10:35 UTC, jserv commented on scripts/build_riscv_tests.sh
> +OBJCOPY=${RISCV}/bin/riscv64-unknown-elf-objcopy
Introduce the variable `CROSS_COMPILE`.

2022-07-15 10:40 UTC, jserv commented on Makefile
> +	scripts/build_riscv_tests.sh
Check file permission. Executable.

2022-07-15 10:41 UTC, jserv commented on Makefile
> +test: all
The directory name should be `tests`, and the target in `Makefile` would be `riscv-tests`.

2022-07-15 10:43 UTC, jserv commented on Makefile
> +	scripts/build_riscv_tests.sh
Add proper `git clone` to get `riscv-tests` repository here.

2022-07-15 10:43 UTC, jserv commented on semu.c
> +        // printf("a0 = 0x%lx\n", cpu->regs[10]);
Don't leave the dead code.

2022-07-15 10:45 UTC, jserv commented on test/test.c
> +    add_testdata("rv64ui_p_add", "./test/riscv-tests-data/rv64ui_p_add"),
Replace all occurrences of `./test/` with `tests/`.

2022-07-15 10:48 UTC, jserv requested changes
Follow the directory structure of rv32emu.
See https://github.com/sysprog21/rv32emu/tree/master/tests

Avoid preserving the binary blob in git repository. Instead, generate via script(s).

2022-07-15 10:53 UTC, jserv commented on Makefile
>  all:
Modularize the build system. i.e., there should be something like `ENABLE_RISCV_TESTS` which can be turned on/off on demand.
See https://github.com/sysprog21/rv32emu/blob/master/Makefile

2022-07-15 10:55 UTC, jserv commented on semu.c
> +void semu_test_start(int argc, char **argv)
Add the statement before the test oriented functions. i.e.,
```c
#ifdef ENABLE_RISCV_TESTS
void semu_test_start(int argc, char **argv)
{
```

2022-07-15 10:56 UTC, jserv commented on semu.c
> +            uint64_t inst;
Use `insn` instead of `inst`. See `git log` for details.

2022-07-15 11:01 UTC, jserv commented on include/test.h
> +#ifndef __TEST_H__
Move `include/test.h` to `tests/test.h` and don't rely on `-I` option. Specify the relative path -- `#include "tests/test.h"`

2022-07-15 11:24 UTC, gagachang commented
Thanks, I need some time to modify them.
Please wait for my update.

2022-07-15 18:25 UTC, gagachang commented on include/test.h
> +#ifndef __TEST_H__
done

2022-07-15 18:25 UTC, gagachang commented on semu.c
> +            uint64_t inst;
done

2022-07-15 18:26 UTC, gagachang commented on scripts/build_riscv_tests.sh
> +OBJCOPY=${RISCV}/bin/riscv64-unknown-elf-objcopy
Done, CROSS_COMPILE is defined in Makefile

2022-07-15 18:27 UTC, gagachang commented on Makefile
> +	scripts/build_riscv_tests.sh
I removed this script file since Makefile is enough for us

2022-07-15 18:28 UTC, gagachang commented on Makefile
> +	scripts/build_riscv_tests.sh
The riscv-tests is submodule now.

2022-07-15 18:30 UTC, gagachang commented on semu.c
> +        // printf("a0 = 0x%lx\n", cpu->regs[10]);
Fixed.

2022-07-15 18:30 UTC, gagachang commented on test/test.c
> +    add_testdata("rv64ui_p_add", "./test/riscv-tests-data/rv64ui_p_add"),
Done

2022-07-15 18:33 UTC, gagachang commented on Makefile
>  all:
ENABLE_RISCV_TESTS is added into Makefile now.
The test.o is only compiled and linked into semu when this flag equals one.

2022-07-16 03:20 UTC, jserv commented on Makefile
> +CROSS_COMPILE = riscv64-unknown-elf-
Change to `CROSS_COMPILE ?= riscv64-unknown-elf-` which allows overrides.

2022-07-16 03:23 UTC, jserv commented on tests/test.c
> +#include <stdio.h>
Rename `tests/test.c` to `tests/isa-test.c` which emphasizes on its purpose.

2022-07-16 03:29 UTC, jserv commented on semu.c
> +    if (!strncmp(argv[1], "--test", strlen("--test")))
You can simply hardcode `6` instead of invoking `strlen("--test")` since it is not necessary to make function calls here.

2022-07-16 03:30 UTC, jserv commented on semu.c
> +        semu_test_start(argc, argv);
Once you change the function prototype to `int semu_test_start(int argc, char **argv)`, you can rewrite as following:
```c
    if (!strncmp(argv[1], "--test", 6))
        return semu_test_start(argc, argv);

```

2022-07-16 03:31 UTC, jserv commented on semu.c
> +        semu_start(argc, argv);
Ditto. If you change the function prototype of semu_start, you can simplify as following:
```c
    return semu_start(argc, argv);
```

2022-07-16 03:34 UTC, jserv commented on Makefile
> +build-riscv-tests:
Add a new target:
```
tests/riscv-tests:
    git submodule update --init
```

And `build-riscv-tests` target should depend on tests/riscv-tests.

2022-07-16 03:49 UTC, jserv commented on tests/test.h
> +#define add_testdata(n, path)                              \
A macro should have its name all capitalize. i.e., `ADD_INSN_TEST`.
Since we assume the directory structure, we can rewrite as following:
```c
#define ADD_INSN_TEST(op) \
    { .result = TEST_FAIL, \
      .name = op, \
      .file_path = "tests/riscv-tests-data/" #op, \
    }
```

See https://gcc.gnu.org/onlinedocs/gcc-12.1.0/cpp/Stringizing.html

2022-07-16 03:54 UTC, jserv commented on tests/test.c
> +            printf("\033[0;31mFail: %s\033[0m\n", riscv_tests[n].name);
Move ANSI control codes to dedicated macros.
See https://github.com/sysprog21/threaded-logger/blob/master/colors.h

2022-07-16 03:57 UTC, jserv commented on tests/test.c
> +struct testdata *get_testdata(void)
It is not worth defining two functions which refer to static data. Drop them and use macro such as `ARRAY_SIZE`.

2022-07-16 03:58 UTC, jserv commented on tests/test.c
> +struct testdata riscv_tests[] = {
Add modifier `static const`.

2022-07-16 04:01 UTC, jserv commented on semu.c
> +
Add `extern` here.
```c
extern struct testdata riscv_tests[];
```

2022-07-16 15:40 UTC, gagachang commented on semu.c
> +
Hi, I found a problem.
If we add ```extern``` here, we can not use sizeof() to calculate the size of riscv_tests[] in compile time.
How about maintaining another variable called ```riscv_tests_nr``` to store the size and ```extern``` it?

```
int riscv_tests_nr = sizeof(riscv_tests) / sizeof(struct testdata);
extern int riscv_tests_nr;
```

2022-07-16 15:46 UTC, gagachang commented on tests/test.c
> +struct testdata riscv_tests[] = {
```struct testdata``` has a **result** member to store the test result, and it is initialized as TEST_FAIL.
When SEMU runs a test correctly, it will assign result as TEST_PASS.
So this array could not be const if we have this purpose.

```
struct testdata {
    int result;
    const char *name;
    const char *file_path;
};
```

Is it really necessary to be const variable?

2022-07-16 15:59 UTC, jserv commented on tests/test.c
> +struct testdata riscv_tests[] = {
Both field `name` and `file_path` must be declared as `const` while field `result` can be writable.

2022-07-16 16:01 UTC, jserv commented on semu.c
> +
Using another `extern` variable sounds fine. Rename it to `n_riscv_tests` for short.

2022-07-16 16:07 UTC, gagachang commented on Makefile
> +CROSS_COMPILE = riscv64-unknown-elf-
Done!

2022-07-16 16:08 UTC, gagachang commented on semu.c
> +    if (!strncmp(argv[1], "--test", strlen("--test")))
Done!

2022-07-16 16:08 UTC, gagachang commented on semu.c
> +        semu_test_start(argc, argv);
Done!

2022-07-16 16:08 UTC, gagachang commented on Makefile
> +build-riscv-tests:
Done

2022-07-16 16:09 UTC, gagachang commented on tests/test.c
> +            printf("\033[0;31mFail: %s\033[0m\n", riscv_tests[n].name);
Done. Add three macros for reset color, dark red and dark green over this function.

2022-07-16 16:10 UTC, gagachang commented on semu.c
> +
Done. The two ```extern``` variables are defined in ```test/test.h```.

2022-07-16 16:11 UTC, jserv commented on semu.c
> +            else if (tohost != 0)
Replace "else if" with "if" for readability.

2022-07-16 16:12 UTC, jserv commented on semu.c
> +    else
Remove this "else" since it is not necessary.

2022-07-16 16:17 UTC, jserv commented on Makefile
> +riscv-tests: all build-riscv-tests
Target `riscv-tests` should depend on `$(BIN)` rather than `all` because we might extend the goal of `all` later.

2022-07-16 16:27 UTC, jserv commented on .gitmodules
> +	url = https://github.com/riscv-software-src/riscv-tests.git
Get rid of suffix `.git` from `url`. i.e., specify `url = https://github.com/riscv-software-src/riscv-tests`

2022-07-16 16:30 UTC, gagachang commented on Makefile
> +riscv-tests: all build-riscv-tests
OK, I think we also need to remove test binary folder when we ```make distclean```.

```
distclean: clean
	rm -f kernel.bin fs.img
	rm -rf $(RISCV_TESTS_BIN_DIR)
```

2022-07-16 16:32 UTC, jserv commented on Makefile
> +tests/riscv-tests:
Replace `tests/riscv-tests` with `tests/riscv-tests/configure` because we have to track the files in directory `riscv-tests`.

2022-07-16 16:33 UTC, jserv commented on Makefile
> +	cd $(RISCV_TESTS_DIR); autoconf; ./configure --prefix=$(RISCV_TESTS_TARGET_DIR)
Is it required to run `autoconf` before the execution of `configure` script?

2022-07-16 16:35 UTC, jserv commented on Makefile
> +riscv-tests: all build-riscv-tests
Exactly, let `dist-clean` target work as expected.

2022-07-16 16:36 UTC, jserv commented on tests/isa-test.c
> +
Add a new blank line before displaying test results.

2022-07-16 16:37 UTC, gagachang commented on Makefile
> +	cd $(RISCV_TESTS_DIR); autoconf; ./configure --prefix=$(RISCV_TESTS_TARGET_DIR)
I just follow the steps provided from riscv-tests.
The README of riscv-tests says:

```
$ git clone https://github.com/riscv/riscv-tests
$ cd riscv-tests
$ git submodule update --init --recursive
$ autoconf
$ ./configure --prefix=$RISCV/target
$ make
$ make install
```

2022-07-16 16:38 UTC, jserv requested changes
Add the reference test result at the end of git commit message. e.g.,
```
=======================
Test result: 53/71
=======================
```

The git HEAD of riscv-tests should be mentioned as well.

2022-07-16 16:39 UTC, jserv commented on Makefile
> +	cd $(RISCV_TESTS_DIR); autoconf; ./configure --prefix=$(RISCV_TESTS_TARGET_DIR)
Check if "autoconf" is necessary, otherwise we have to document automake/autoconf as dependent packages.

2022-07-16 16:47 UTC, jserv commented on Makefile
> +	cd $(RISCV_TESTS_DIR); autoconf; ./configure --prefix=$(RISCV_TESTS_TARGET_DIR)
In addition, check if `make install` is a necessary step.

2022-07-16 16:51 UTC, jserv commented on Makefile
> +	cd $(RISCV_TESTS_DIR); autoconf; ./configure --prefix=$(RISCV_TESTS_TARGET_DIR)
We might run riscv-tests with GitHub Actions, so that we can validate pull requests automatically. See [SSE2NEON](https://github.com/DLTcollab/sse2neon/actions) as an example.
It would be vital if we can eliminate unnecessary commands/steps since the shortened CI pipeline implies less time to wait.

2022-07-16 16:53 UTC, jserv commented on Makefile
> +	cd $(RISCV_TESTS_DIR); autoconf; ./configure --prefix=$(RISCV_TESTS_TARGET_DIR)
Can you skip the generation of RV32 specific files?

2022-07-16 16:56 UTC, gagachang commented on Makefile
> +	cd $(RISCV_TESTS_DIR); autoconf; ./configure --prefix=$(RISCV_TESTS_TARGET_DIR)
Sure.
Let me pull a new patch for other comments.
I will check build flow of riscv-tests later.

2022-07-16 17:03 UTC, gagachang commented on tests/isa-test.c
> +
Done. Now we display test result as:

```
...
Fail: rv64ua_p_amoxor_w
Fail: rv64ua_p_lrsc

=======================
Test result: 53/71
=======================
```

2022-07-16 17:03 UTC, gagachang commented on Makefile
> +tests/riscv-tests:
Done

2022-07-16 17:10 UTC, merged

2022-07-16 17:33 UTC, gagachang commented on Makefile
> +	cd $(RISCV_TESTS_DIR); autoconf; ./configure --prefix=$(RISCV_TESTS_TARGET_DIR)
> Can you skip the generation of RV32 specific files?

Refer to their [isa test Makefile](https://github.com/riscv-software-src/riscv-tests/blob/master/isa/Makefile), it seems they always build RV32 tests. Only RV64 is optional.

But we can build isa tests only  by
```
make isa
```

Also, ```make install``` is unnecessary since it just copies generated files into another directory.