Implement virtio-gpu with 2D rendering mode
jserv/semu pull request #34
Opened 2023-11-09 14:41 UTC by shengwen-tw

## Overview

This pull request adds basic virtio-gpu support for semu (conformed to spec. 1.2), which comprises the following changes:

* Implement virtio-gpu device with 2D rendering mode, in which the PIXMAN and SDL libraries are used.
* Enable virtio-gpu kernel module
* Enable virtio-gpu in the device tree source
* Extend initrd region size to 35 MiB for containing virio-gpu moudles (~30 MiB)
* Enable `libdrm` from Buildroot setting
* Enable `depmod` from BusyBox setting as it is essential for using `modprobe` command
* Add shell script for packing kernel modules and launch script into the initrd image

## Implemented Commands

* `VIRTIO_GPU_CMD_GET_DISPLAY_INFO`: Notifying the guest about the display size and state (i.e., enabled or disabled).
* `VIRTIO_GPU_CMD_RESOURCE_CREATE_2D`:  Notifying the host to prepare data structure for storing image.
* `VIRTIO_GPU_CMD_RESOURCE_UNREF`: Notifying the host to destroy data structure of a 2D resource.
* `VIRTIO_GPU_CMD_GET_EDID`: Notifying the guest about the virtual connector's information (i.e., display).
* `VIRTIO_GPU_CMD_GET_CAPSET_INFO`: Notifying the guest the display capability sets.
* `VIRTIO_GPU_CMD_SET_SCANOUT`: Notifying the host to know which scanout (i.e., display) should link to which 2D resource.
* `VIRTIO_GPU_CMD_RESOURCE_FLUSH`: Notifying the host that the image data is ready to render.
* `VIRTIO_GPU_CMD_TRANSFER_TO_HOST_2D`: Notifying the host to copy the image data from the guest.
* `VIRTIO_GPU_CMD_RESOURCE_ATTACH_BACKING`: Notifying the host to record some memory pages (for storing image) for a 2D resource.

## Test Procedures

1. Install SDL

```
git clone https://github.com/libsdl-org/SDL.git -b SDL2
cd SDL
mkdir build
cd build
../configure
make
sudo make install
```

2. Install Pixman

```
git clone https://github.com/libpixman/pixman.git
cd pixman/
./autogen.sh 
make -j$(nproc)
sudo make install
```

3. Build `semu`

```
cd semu/
make
```

4. Build virtio-gpu test image

```
./scripts/create-initrd-img.sh
```

5. Launch `semu`:

```
make check
```

6. After `semu` is launched, log in and execute `run.sh` to load the modules:

```
mkdir mnt
mount /dev/vda mnt
cd mnt
sh ./run.sh
```

7. After the modules are loaded, type:

```
modetest -M virtio_gpu -s 34:1024x768
```

A test image should then show up in the display window.

**Reference output (text-only):**

```
Welcome to Buildroot
buildroot login: root
# mkdir mnt
# mount /dev/vda mnt
[   21.086929] EXT4-fs (vda): recovery complete
[   21.087346] EXT4-fs (vda): mounted filesystem with ordered data mode. Quota mode: disabled.
# cd mnt
# sh ./run.sh
[   42.533320] [drm] features: -virgl +edid -resource_blob -host_visible
[   42.533399] [drm] features: -context_init
[   42.535654] [drm] number of scanouts: 1
[   42.535836] [drm] number of cap sets: 0
[   42.542754] [drm] Initialized virtio_gpu 0.1.0 0 for f4300000.virtio on minor 0
# modetest -M virtio_gpu -s 34:1024x768
setting mode 1024x768-60.00Hz on connectors 34, crtc 33
[   62.780039] virtio-mmio f4300000.virtio: [drm] drm_plane_enable_fb_damage_clips() not called
failed to set gamma: Function not implemented
```

2023-11-11 19:27 UTC, jserv commented
How about using [virglrenderer](https://gitlab.freedesktop.org/virgl/virglrenderer)?
See https://mail.gnu.org/archive/html/qemu-devel/2021-02/msg04235.html

2023-11-15 13:55 UTC, shengwen-tw commented
Yes, I do plan to support VirGL for acceleration.

As far as I know, the offloading of rendering operations to the host GPU is called 3D mode by VirtIO's spec, whereas this pull request only implemented 2D mode due to the overall complexity.

Before implementing 3D rendering mode with VirGL, I think we need to configure the Buildroot to have a minimal desktop environment or set the Mesa benchmark tools without a desktop manager (I'm not sure if this is feasible).

In conclusion, I'll recommend first merging this pull request as a checkpoint for virtio-gpu and then adding support for VirGL in a later pull request.

2024-01-23 12:30 UTC, jserv requested changes
Rebase and resolve the conflicts.

2024-01-25 08:14 UTC, jserv commented on README.md
> +### SDL2 Installation
It is not necessary to build SDL2 and pixman. Let's make use of prebuilt packages.

2024-01-25 08:50 UTC, shengwen-tw commented
Reference: [How to run headless unit tests for GUIs on GitHub actions](https://arbitrary-but-fixed.net/2022/01/21/headless-gui-github-actions.html)

2024-01-26 05:28 UTC, jserv commented on Makefile
> +ENABLE_PIXMAN ?= 1
Pixman might be absent for some platforms such as macOS and Windows. Can you get rid of it?

2024-01-26 05:59 UTC, shengwen-tw commented on Makefile
> +ENABLE_PIXMAN ?= 1
It seems like [Homebrew](https://formulae.brew.sh/formula/pixman) does exist a pre-built package of Pixman. (For Windows, the problem seems a bit tricky)

If we decide to handle the low-level pixel manipulation by ourselves, we may need to support various image formats as shown in [here](https://github.com/shengwen-tw/semu/blob/master/virtio-gpu.c#L292).
Please let me know about your opinion.

2024-01-26 06:06 UTC, jserv commented on Makefile
> +ENABLE_PIXMAN ?= 1
Should the requirement be limited to performing color space conversion, we can offer a streamlined implementation specifically for this purpose.

2024-01-26 17:22 UTC, jserv commented
Rather than relying on Xvfb as a heavy-duty solution for validating Linux DRM/framebuffer, it might be more efficient to use lighter tools like [drm-framebuffer](https://github.com/embear-engineering/drm-framebuffer). This tool, designed for testing drm devices, takes data from stdin and displays it, offering a simpler and more straightforward approach.

2024-01-27 13:17 UTC, shengwen-tw commented
> Rather than relying on Xvfb as a heavy-duty solution for validating Linux DRM/framebuffer, it might be more efficient to use lighter tools like [drm-framebuffer](https://github.com/embear-engineering/drm-framebuffer). This tool, designed for testing drm devices, takes data from stdin and displays it, offering a simpler and more straightforward approach.

Actually, the idea of using Xvfb here is to make sure the SDL window can be launched in the CI environment by GitHub Action.

2024-01-31 09:31 UTC, shengwen-tw commented on Makefile
> +ENABLE_PIXMAN ?= 1
It turns out that it requires not much modification to remove the dependency of the Pixman.
We only need to allocate the image buffer properly and manage the stride size and image depth (i.e., Bits per Pixel).

2024-01-31 11:25 UTC, jserv commented on Makefile
> +ENABLE_SDL ?= 1
The virtio-gpu support depends on SDL, so that you have to check the rationale.

2024-01-31 11:29 UTC, jserv commented on window.h
> +void display_window_init(void);
Change the prefix for functions specific to window management to "window_" from "display_window."

2024-01-31 11:33 UTC, jserv commented on Makefile
> +CFLAGS := -O2 -g -Wall -Wextra -Wno-unused-function
Don't change this flag. We should always check unused functions.

2024-01-31 11:34 UTC, jserv commented on Makefile
> +CFLAGS += `sdl2-config --cflags`
Use `$(shell sdl2-config --cflags)` instead.

2024-01-31 11:35 UTC, jserv commented on configs/linux.config
> +#
Remove these lines.

2024-01-31 11:37 UTC, jserv commented on configs/linux.config
> +CONFIG_I2C=m
See if i2c configuration is required.

2024-02-01 02:07 UTC, shengwen-tw commented on configs/linux.config
> +CONFIG_I2C=m
The I2C could not be disabled as it is required by the DRM module even if virtio-gpu doesn't really on it.

2024-02-01 08:49 UTC, jserv commented
Merely executing `Xvfb :1 -screen 0 1600x1200x24` is inadequate because, although it confirms the initialization of SDL with libX11, it does not guarantee the accuracy of the window content rendered in Xvfb.

2024-02-01 13:44 UTC, shengwen-tw commented on configs/linux.config
> +#
Resolved.

2024-02-01 13:44 UTC, shengwen-tw commented on Makefile
> +CFLAGS += `sdl2-config --cflags`
Resolved.

2024-02-01 13:45 UTC, shengwen-tw commented on Makefile
> +CFLAGS := -O2 -g -Wall -Wextra -Wno-unused-function
Resolved.

2024-02-01 13:46 UTC, shengwen-tw commented on window.c
> +void display_window_render(uint32_t id,
Check [[1]](https://github.com/shengwen-tw/semu/blob/master/virtio-gpu.c#L40) and [[2]](https://github.com/shengwen-tw/semu/blob/master/window.c#L131).

2024-02-01 13:53 UTC, shengwen-tw commented
> Merely executing `Xvfb :1 -screen 0 1600x1200x24` is inadequate because, although it confirms the initialization of SDL with libX11, it does not guarantee the accuracy of the window content rendered in Xvfb.

The latest modification allows the virtio-gpu to be run without SDL, so the current CI test can pass by executing `make ENABLE_SDL=0`.

2024-02-01 13:55 UTC, shengwen-tw commented on window.h
> +void display_window_init(void);
Resolved.

2024-02-01 13:55 UTC, shengwen-tw commented on Makefile
> +ENABLE_SDL ?= 1
Resolved.

2024-02-01 14:40 UTC, jserv commented on virtio-gpu.c
> +    if (res_2d->image)
Remove this `if` statement.

2024-02-01 14:41 UTC, jserv commented on virtio-gpu.c
> +        if (res_2d->image)
Quote from Linux Programmer's Manual
> If ptr is NULL, no operation is performed.

Remove unnecessary `if` statement before the invocation of `free`.

2024-02-01 14:43 UTC, jserv commented on window.c
> +int window_thread(void *data)
`window_thread` is not a public function. Make it private by declaring `static`.

2024-02-01 14:44 UTC, jserv commented on window.h
> +void display_resource_lock(uint32_t id);
Rename to `window_lock` and `window_unlock`.

2024-02-01 15:40 UTC, shengwen-tw commented on window.c
> +int window_thread(void *data)
Resolved.

2024-02-01 15:40 UTC, shengwen-tw commented on virtio-gpu.c
> +        if (res_2d->image)
Resolved.

2024-02-01 15:40 UTC, shengwen-tw commented on virtio-gpu.c
> +    if (res_2d->image)
Resolved.

2024-02-01 22:12 UTC, jserv commented on configs/buildroot.config
> +BR2_HAVE_DOT_CONFIG=y
Put only the necessary configuration items in this file. Minimize the necessary changes.

2024-02-01 22:23 UTC, jserv commented on scripts/run.sh
> +#!/usr/bin/bash
All files in the scripts directory are implicitly designed to run on the host system. Conversely, if a file is specifically intended for the RV32 target, it should not be placed in this directory.

2024-02-01 22:24 UTC, jserv commented on scripts/run.sh
> +depmod -a
It is not necessary to run `depmon` inside RV32 target. Instead, check https://unix.stackexchange.com/questions/401138

2024-02-01 22:29 UTC, jserv commented on window.c
> +#include <pthread.h>
For the sake of portability, don't include `<pthread.h>` or `<semaphore.h`>. Instead, place `#include <SDL_thread.h>` as a generic solution.

2024-02-01 22:32 UTC, jserv commented on window.c
> +    display->window = SDL_CreateWindow("Semu", SDL_WINDOWPOS_UNDEFINED,
Use lowercase `semu`.

2024-02-01 22:33 UTC, jserv commented on window.c
> +    char thread_name[100] = {0};
It is not worthy to specify lengthy string.

2024-02-01 22:35 UTC, jserv commented on window.c
> +    displays[id].width = display->width;
Can you utilize `memcpy` for such initialization? Be aware of structure packing.

2024-02-01 22:36 UTC, jserv commented on window.h
> +void window_resource_lock(uint32_t id);
Simply name it `window_lock` and `window_unlock` since their names already imply the shared resource management.

2024-02-02 09:24 UTC, jserv commented on configs/buildroot.config
> +BR2_HAVE_DOT_CONFIG=y
I am concerned about the increasing size of both the Linux kernel and the root file system. The suggested updates allow the emulator to be tailored based on selected features like virtio-gpu. However, from the viewpoint of buildroot, it involves a single build process that decides on the package compilation without recognizing the configurable features.

2024-02-03 17:09 UTC, shengwen-tw commented on configs/buildroot.config
> +BR2_HAVE_DOT_CONFIG=y
I received the following error after attempting to modify the intrinsic parameter manually:

```
$ make
Makefile:943: *** Please configure Buildroot first (e.g. "make menuconfig").  Stop.
make: *** [Makefile:82: _all] Error 2
```

It seems like the Buildroot doesn't want to allow the user to modify the `.config` file without `make menuconfig`.

2024-02-03 17:13 UTC, shengwen-tw commented on scripts/run.sh
> +#!/usr/bin/bash
`run.sh` is now relocated to the newly created directory `guest/` .

2024-02-03 17:15 UTC, shengwen-tw commented on scripts/run.sh
> +depmod -a
Resolved by invoking `make install_modules` to build the `modules.dep` file. (d9472b0553eab900cfcb753ffc7910c83c1c4735)

2024-02-03 17:16 UTC, shengwen-tw commented on window.c
> +#include <pthread.h>
Resolved.

2024-02-03 17:16 UTC, shengwen-tw commented on window.c
> +    display->window = SDL_CreateWindow("Semu", SDL_WINDOWPOS_UNDEFINED,
Resolved.

2024-02-03 17:17 UTC, shengwen-tw commented on window.c
> +    char thread_name[100] = {0};
Resolved by shrinking the size from 100 to 20. Check [window.c#L98](https://github.com/shengwen-tw/semu/blob/master/window.c#L98).

2024-02-03 17:18 UTC, shengwen-tw commented on window.c
> +    displays[id].width = display->width;
Check 965aad4fe883d79c071a2457b7f6a99ca7cb2e46.

2024-02-03 17:18 UTC, shengwen-tw commented on window.h
> +void window_resource_lock(uint32_t id);
Resolved.

2024-02-04 01:18 UTC, jserv commented on configs/buildroot.config
> +BR2_HAVE_DOT_CONFIG=y
Of course, you shall keep `BR2_HAVE_DOT_CONFIG`. Meanwhile, you can shrink the lines of configuration file.

2024-02-05 17:10 UTC, jserv commented on Makefile
> +ifeq ($(ENABLE_VIRTIOGPU),1)
If SDL is absent, there should be no support for `ENABLE_VIRTIOGPU`.

2024-02-06 14:36 UTC, shengwen-tw commented on configs/buildroot.config
> +BR2_HAVE_DOT_CONFIG=y
The following three lines are the essential settings for enabling DRM in Builtroot:

```
BR2_PACKAGE_LIBDRM=y
BR2_PACKAGE_LIBDRM_HAS_ATOMIC=y
BR2_PACKAGE_LIBDRM_INSTALL_TESTS=y
```

However, after executing `make olddefconfig`, the Buildroot will still append several lines in `.config` to keep the configuration file up to date of the latest version of Buildroot.

2024-02-07 12:28 UTC, shengwen-tw commented on Makefile
> +ifeq ($(ENABLE_VIRTIOGPU),1)
Resolved in 7985adc17c9a3a4e01f4a470dfba0851f3d2ed14.

2024-02-14 11:51 UTC, jserv commented on window.c
> +void window_render(void *_resource)
Avoid specifying the type of parameters to `void *` if the function is not designed for generic usage.

2024-02-16 11:35 UTC, shengwen-tw commented on window.c
> +void window_render(void *_resource)
Resolved in 12a76086abbdd9bbc10a0d3377b857cb54212aa8.

2024-05-15 05:32 UTC, jserv commented
I dislike the inclusion to target the X Window System for 2D rendering verification in minimalist system emulators like `semu`. We could instead leverage existing packages that render graphical content directly to the Linux framebuffer, supported by the proposed virtio-gpu path. On the other hand, the installation and footprint of the X Window System are generally larger, resulting in limited functionality with minimal installations.

2024-05-15 13:19 UTC, shengwen-tw commented
> I dislike the inclusion to target the X Window System for 2D rendering verification in minimalist system emulators like `semu`. We could instead leverage existing packages that render graphical content directly to the Linux framebuffer, supported by the proposed virtio-gpu path. On the other hand, the installation and footprint of the X Window System are generally larger, resulting in limited functionality with minimal installations.

How about using DirectFB with Mesa? Here is a [FOSDEM presentation](https://archive.fosdem.org/2022/schedule/event/directfb/attachments/slides/5077/export/events/attachments/directfb/slides/5077/fosdem_2022_directfb2.pdf) I found.
One of the reasons I included X Window System is because later we can test 3D rendering mode (i.e., VirGL) with it.

2024-05-15 13:27 UTC, jserv commented
> How about using DirectFB with Mesa? Here is a [FOSDEM presentation](https://archive.fosdem.org/2022/schedule/event/directfb/attachments/slides/5077/export/events/attachments/directfb/slides/5077/fosdem_2022_directfb2.pdf) I found. One of the reasons I included X Window System is because later we can test 3D rendering mode (i.e., VirGL) with it.

[DirectFB2](https://directfb2.github.io/) (the active DirectFB fork) is really amazing. If buildroot is capable of building DirectFB2 packages from scratch, I would like to integrate it as the major showcase.

2024-05-30 16:26 UTC, jserv requested changes
Rebase the latest `master` branch.

2024-06-05 09:42 UTC, jserv commented on configs/linux.config
> +CONFIG_FB_CFB_FILLRECT=m
Drop framebuffer modules. Enable the minimal functionality for Linux framebuffer.

2024-06-05 09:56 UTC, shengwen-tw commented on configs/linux.config
> +CONFIG_FB_CFB_FILLRECT=m
I'm in an intense work period of my job (until ~July), so I will adjust the pull request after that.
By the way, `semu` can now run `DirectFB2` with default examples now, I will provide detailed information later.

2024-06-16 09:04 UTC, jserv commented on scripts/build-image.sh
> +    wget https://gist.githubusercontent.com/shengwen-tw/e5dffd8aefd7d2019cfbb4b7f1048ef3/raw/b079443aefb965742a6c6227fe4d0cf831d87cb1/riscv-directfb2.patch
Don't do that. You can create a directory named `patches` and place the corresponding patches against the packages you want to patch.

2024-06-16 09:05 UTC, jserv commented on scripts/build-image.sh
> +    wget https://gist.githubusercontent.com/shengwen-tw/e5dffd8aefd7d2019cfbb4b7f1048ef3/raw/b079443aefb965742a6c6227fe4d0cf831d87cb1/riscv-directfb2.patch
Eventually, you should promote the DirectFB2 inclusion for the buildroot project. Get it adopted by upstream.

2024-06-17 04:04 UTC, jserv commented on minimal.dts
> +        /* XXX: 105MiB */
Refine the comment.

2024-06-17 04:05 UTC, jserv commented on guest/run.sh
> +#!/usr/bin/bash
Rename the directory `guest` to `target` as [kvm-host](https://github.com/sysprog21/kvm-host) does.

2024-06-17 15:49 UTC, shengwen-tw commented
Git-pushed for progress saving.
`linux.config` and `buildroot.config` are still subjected to change (i.e., disable unused functionalities).
The proper size for `initrd` space will be calculated after size reduction.

2024-06-17 15:50 UTC, shengwen-tw commented on guest/run.sh
> +#!/usr/bin/bash
Resolved.

2024-06-17 15:51 UTC, shengwen-tw commented on scripts/build-image.sh
> +    wget https://gist.githubusercontent.com/shengwen-tw/e5dffd8aefd7d2019cfbb4b7f1048ef3/raw/b079443aefb965742a6c6227fe4d0cf831d87cb1/riscv-directfb2.patch
> Don't do that. You can create a directory named `patches` and place the corresponding patches against the packages you want to patch.

Resolved.

2024-06-17 15:57 UTC, shengwen-tw commented on scripts/build-image.sh
> +    wget https://gist.githubusercontent.com/shengwen-tw/e5dffd8aefd7d2019cfbb4b7f1048ef3/raw/b079443aefb965742a6c6227fe4d0cf831d87cb1/riscv-directfb2.patch
> Eventually, you should promote the DirectFB2 inclusion for the buildroot project. Get it adopted by upstream.

I'll tag the pull request link of DirectFB2 inclusion for Buildroot at #32 once it is ready.

2024-06-17 18:02 UTC, jserv commented on scripts/build-image.sh
> +    wget https://gist.githubusercontent.com/shengwen-tw/e5dffd8aefd7d2019cfbb4b7f1048ef3/raw/b079443aefb965742a6c6227fe4d0cf831d87cb1/riscv-directfb2.patch
> I'll tag the pull request link of DirectFB2 inclusion for Buildroot at #32 once it is ready.

Good. In this repository, we aim to build packages minimally by using established tools like buildroot. Therefore, prioritizing upstream contributions is a fundamental principle for this purpose.

2024-06-18 16:13 UTC, shengwen-tw commented on minimal.dts
> +        /* XXX: 105MiB */
Resolved.

2024-06-18 16:14 UTC, shengwen-tw commented
Discard changes for `buildroot.config` as no additional feature is needed for enabling DirectFB2 with virtio-gpu.

2024-06-27 16:03 UTC, shengwen-tw commented
Discard patch to the `DirectFB2` as the modification is accepted by the maintainer.

2024-07-01 23:03 UTC, jserv commented
We can enable SDL support through configuration changes, but the BusyBox-specific settings generate much larger filesystem images, unsuitable for minimal usage. Can you suggest an effective way to switch or customize these settings?

2024-07-02 15:16 UTC, shengwen-tw commented
> We can enable SDL support through configuration changes, but the BusyBox-specific settings generate much larger filesystem images, unsuitable for minimal usage. Can you suggest an effective way to switch or customize these settings?

I think we now have no modification to `BusyBox`'s setting now as they were dropped in an earlier version.
This pull request currently only modifies `linux.config` with the following new features enabled:
1. virtio-gpu driver
2. fbdev (Linux Framebuffer) subsystem
3. DRM subsystem (Required by virtio-gpu)
4. HDMI driver (Force selected by DRM)
5. I2C driver (Force selected by DRM)
6. DMA shared buffer feature (Force selected by DRM)

According to the Kconfig files from the Linux kernel:

```diff
config DRM_VIRTIO_GPU
        tristate "Virtio GPU driver"
>        depends on DRM && VIRTIO_MENU && MMU
        select VIRTIO
        select DRM_KMS_HELPER
        select DRM_GEM_SHMEM_HELPER
        select VIRTIO_DMA_SHARED_BUFFER
        help
           This is the virtual GPU driver for virtio.  It can be used with
           QEMU based VMMs (like KVM or Xen).

           If unsure say M.
```

```diff
menuconfig DRM
        tristate "Direct Rendering Manager (XFree86 4.1.0 and higher DRI support)"
        depends on (AGP || AGP=n) && !EMULATED_CMPXCHG && HAS_DMA
        select DRM_NOMODESET
        select DRM_PANEL_ORIENTATION_QUIRKS
>        select HDMI
>        select FB_CMDLINE
>        select I2C
        select I2C_ALGOBIT
>        select DMA_SHARED_BUFFER
        select SYNC_FILE
...
```

Also, since `SDL2` is compiled with `semu` as a part of the host, I think it is not related to `.config` file setting.

2024-07-05 13:30 UTC, shengwen-tw commented
A `Buildroot` patch that added support for `DirectFB2` is submitted via mailing list.
For the code modification, please refer to https://github.com/shengwen-tw/buildroot/commit/aad03b5b786028e61cf602677adfde2324a5939c.

2024-08-26 03:18 UTC, jserv commented
Can you provide a video recording demonstrating virtio-gpu support in RISC-V system emulation, showcasing graphics rendering and input interactions?

2024-08-26 15:57 UTC, jserv commented on configs/buildroot.config
> +BR2_HAVE_DOT_CONFIG=y
Strip `buildroot.config` and utilize `oldconfig` to merge the proposed changes.

2024-08-26 15:59 UTC, jserv commented on configs/linux.config
> +CONFIG_INPUT_JOYSTICK=y
Remove unused joystick.

2024-08-26 16:00 UTC, jserv commented on configs/linux.config
> +CONFIG_HID_MULTITOUCH=y
Drop this.

2024-09-01 02:38 UTC, jserv commented on virtio-input.c
> +#include <linux/input-event-codes.h>
Can you avoid the inclusion of Linux specific headers?

2024-09-01 02:40 UTC, jserv commented on virtio-input.c
> +#include <linux/input-event-codes.h>
That is, semu should be as portable as possible, capable of running on the environments based on Linux, macOS, and even Windows. If virtio-input is highly coupled with Linux host, there should be explicitly checks.

2024-09-01 02:40 UTC, jserv commented on window.c
> +#include <linux/input-event-codes.h>
Ditto. Avoid the inclusion of Linux specific headers.

2024-09-02 14:28 UTC, jserv commented on bitops.h
> +#ifndef __BITOPS_H__
Only keep the necessary functions and move them to `common.h`.

2024-09-08 15:57 UTC, jserv commented on configs/linux.config
> +CONFIG_NR_CPUS=32
Avoid changing SMP specific configurations.

2024-09-08 15:58 UTC, jserv commented on input-event-codes.h
> +/* SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note */
Don't check in GPL-2.0-only code! Instead, extract the identifiers you need.

2024-09-08 16:00 UTC, jserv commented on window.h
> +#include <SDL.h>
This header has nothing related to SDL2.

2024-09-09 05:20 UTC, jserv commented on Makefile
> +    CFLAGS += `pkg-config virglrenderer --cflags`
Use `$(shell pkg-config ...)` instead.

2024-10-07 07:07 UTC, jserv commented on Makefile
> +ifeq ($(ENABLE_VIRTIOGPU),1)
Why did you check `ENABLE_SDL` here?

2024-10-07 07:09 UTC, jserv commented on configs/linux.config
> +CONFIG_CPU_ISOLATION=y
Change the configurations which are required. Minimize as possible as you can.

2024-10-07 07:10 UTC, jserv commented on scripts/build-image.sh
> +function do_directfb_examples
Merge the function into `do_directfb`.

2024-10-09 13:04 UTC, shengwen-tw commented
> `semu` can now run `DirectFB2` with DRM/KMS mode.
> 
> This is done by enforcing DirectFB2 to run with `X8R8G8B8` format via code modification. (By default DirectFB2 uses `A8R8G8B8` format but this failed to work so far, which requires further investigation)
> 
> `DRM/KMS` is crucial for integrating VirGL to the `semu` project as `Linux framebuffer device` does not trigger any 3D rendering operations.

A change to the DirectFB2 is proposed for resolving the issue:
https://github.com/directfb2/DirectFB2/pull/154

2024-12-02 01:08 UTC, jserv requested changes
Rebase the latest `master` branch to pass CI pipeline for macOS.

2025-01-12 12:37 UTC, shengwen-tw commented
Cross-referencing #68 regarding the unexpected hanging of kmscube.

2025-01-26 15:57 UTC, shengwen-tw commented
First successful attempt to run `glxgears` using Mesa3D / GLX in a VirtIO-GPU 2D rendering environment.
![image](https://github.com/user-attachments/assets/a8fb9ade-93c4-4ab6-9fb4-485b52b95ccf)

2025-03-25 16:11 UTC, jserv requested changes
Rebase the latest `master` branch.

2025-03-25 16:24 UTC, shengwen-tw commented
> Rebase the latest `master` branch.

I'll rebase the code after some cleanup, and maybe request a code review now that we’ve made some progress.

2025-05-13 12:42 UTC, shengwen-tw commented
@jserv :
I propose we begin the code review to merge the current progress in this pull request.
I will open a separate pull request to add support for the 3D rendering mode.

2025-06-15 07:33 UTC, jserv commented on Makefile
> +ENABLE_VIRGL ?= 1
It is confusing to have VirGL here. Add comments.

2025-06-15 07:35 UTC, jserv commented on configs/buildroot.config
> +BR2_PACKAGE_XTERM=y
Don't build X11 specific packages.

2025-06-17 11:37 UTC, shengwen-tw commented on configs/buildroot.config
> +BR2_PACKAGE_XTERM=y
Introduced `--x11` flag in `scripts/build-image.sh` for optional building.

2026-04-25 20:31 UTC, jserv commented
Close in favor of #121 and #122

2026-04-25 20:31 UTC, closed without merging